### ISSUE TITLE
Back us not work 

### ISSUE THREAD

**Issue by HUTCHPOO** [Gioelio/Hack-Google-Password#3]
HZEV BLFI YZXPFK XLWVH
Pvvk gsvhv yzxpfk xlwvh hlnvdsviv hzuv yfg zxxvhhryov.

1. 0127 9539		 6. 3660 0220
2. 1962 7384		 7. 2698 8960
3. 8262 1908		 8. 9394 2193
4. 2234 1006		 9. 9702 2320
5. 4032 9427		10. 2549 0868

(yzigowveroorvih9@tnzro.xln)

* Blf xzm lmob fhv vzxs yzxpfk xlwv lmxv.
* Mvvw nliv? Erhrg sggkh://t.xl/2he
* Gsvhv xlwvh dviv tvmvizgvw lm: 21 Uvyi 2022

**Comment by Gioelio** [comment]
can you rewrite your issue in english, please

**Comment by HUTCHPOO** [comment]
My google account was hack and every account that i own.my self is still hacked with a remote spy.i have passwoord to get for account but not one off my 2 step verification are working.i have been struggle for a month can you please help get me in so i can change passwoordOn 26 Feb 2022 15:38, Gioele Fiorenza ***@***.***> wrote:
can you rewrite your issue in english, please

**Comment by Gioelio** [comment]
Using my script, are you able to generate a valid token for your account?

**Comment by HUTCHPOO** [comment]
I dont have a clue about coding i just to a change on there to try and find someone to help me get in my accounts and remove this spy app on my phone.On 26 Feb 2022 15:44, ***@***.*** wrote:My google account was hack and every account that i own.my self is still hacked with a remote spy.i have passwoord to get for account but not one off my 2 step verification are working.i have been struggle for a month can you please help get me in so i can change passwoordOn 26 Feb 2022 15:38, Gioele Fiorenza ***@***.***> wrote:
can you rewrite your issue in english, please

**Comment by Gioelio** [comment]
Honestly it seems like a bad story to me, my advice is to format the device (maybe first saving those few important things) and then try to recover the accounts.

By the way I seemed to understand that in the first message you sent your backup codes, so I would recommend you to try with those. That is, search the internet for how they are used and follow the google procedures

**Comment by HUTCHPOO** [comment]
I have hard reset my phone 20 time i have live support talk with samsung, microsoft and googleplay, google gmail and there workplace nobody helps just says it not there deparment. .I have had my phone at 3 different it guys for help.my back up code do not work i have tried al of them.i have done google account recover everyday for the last 31 days with no luck.they keep send the link to recover to the email adress that i cant get into.i have been at the police but with no help.thank you anyway, i just keep look for some one that can help me to bypass the 2 step process.so i can just get into my account to change the password and were my google pin is send.On 27 Feb 2022 13:34, Gioele Fiorenza ***@***.***> wrote:
Honestly it seems like a bad story to me, my advice is to format the device (maybe first saving those few important things) and then try to recover the accounts.
By the way I seemed to understand that in the first message you sent your backup codes, so I would recommend you to try with those. That is, search the internet for how they are used and follow the google procedures

**Comment by Gioelio** [comment]
I think that my code can't help you, because if anyone have changed your google's password you aren't able to bypass 2 step verification (because at least you must have your account password), sorry

**Comment by HUTCHPOO** [comment]
I have the account password.On 27 Feb 2022 23:47, Gioele Fiorenza ***@***.***> wrote:
I think that my code can't help you, because if anyone have changed your google's password you aren't able to bypass 2 step verification (because at least you must have your account password), sorry

**Comment by Gioelio** [comment]
But if you try to login in your account with that password you get "wrong password", right?

**Comment by HUTCHPOO** [comment]
No i get right password.then its has the 2 step verification they need.now there is my problem.as the code dont work and the recover email i dont have anymore.so google keep sending the pin i need to my get into my account to the email account i also trying to get into.On 27 Feb 2022 23:51, Gioele Fiorenza ***@***.***> wrote:
But if you try to login in your account with that password you get "wrong password", right?

**Comment by Gioelio** [comment]
Alright, you can also try my script, but i think that without having the 2 step verification you cannot do much more, sorry. If you wanna try the same... first clone my repository on your pc and inside this folder follow the instruction in the README file, if you are able to get google's token of your account you are at the 20

**Comment by HUTCHPOO** [comment]
Thank you i have no clue how to to it but thank you very much for your time.ill will have to find some one local that can do it for me.Sent from my Galaxy
-------- Original message --------From: Gioele Fiorenza ***@***.***> Date: 2022/02/28  10:09  (GMT+02:00) To: Gioelio/Hack-Google-Password ***@***.***> Cc: HUTCHPOO ***@***.***>, Author ***@***.***> Subject: Re: [Gioelio/Hack-Google-Password] Back us not work  (Issue #3) 
Alright, you can also try my script, but i think that without having the 2 step verification you cannot do much more, sorry. If you wanna try the same... first clone my repository on your pc and inside this folder follow the instruction in the README file, if you are able to get google's token of your account you are at the 20
